export const WORKOUTS = [
  {
    id: "A",
    letter: "A",
    name: "General Full-Body",
    description: "Balanced mix of squat, push, pull, and core. Works everything evenly.",
    totalMinutes: 25,
    color: "amber",
    sections: [
      {
        type: "warmup",
        label: "Warm-up",
        durationMinutes: 4,
        exercises: [
          { name: "Jumping Jacks", prescription: "1 min" },
          { name: "Arm Circles", prescription: "30 sec each way" },
          { name: "Hip Circles", prescription: "30 sec each way" },
          { name: "Leg Swings", prescription: "30 sec each leg" },
        ],
      },
      {
        type: "main",
        label: "3-Round Circuit",
        durationMinutes: 18,
        rounds: 3,
        restNote: "Rest ~90 sec between rounds",
        exercises: [
          { name: "Goblet Squat", prescription: "12 reps" },
          { name: "Push-up", prescription: "10 reps" },
          { name: "Kettlebell Row", prescription: "10 reps each" },
          { name: "Reverse Lunge", prescription: "8 reps each leg" },
          { name: "Plank", prescription: "30 sec" },
        ],
      },
      {
        type: "cooldown",
        label: "Cool-down",
        durationMinutes: 3,
        exercises: [
          { name: "Child's Pose", prescription: "45 sec" },
          { name: "Hip Flexor Stretch", prescription: "30 sec each side" },
          { name: "Hamstring Stretch", prescription: "30 sec each leg" },
        ],
      },
    ],
  },
  {
    id: "B",
    letter: "B",
    name: "Pull & Hinge",
    description: "Deadlifts, rows, and swings. Builds a strong posterior chain.",
    totalMinutes: 25,
    color: "teal",
    sections: [
      {
        type: "warmup",
        label: "Warm-up",
        durationMinutes: 4,
        exercises: [
          { name: "Dead Bug", prescription: "45 sec" },
          { name: "Cat-Cow", prescription: "45 sec" },
          { name: "Hip Hinge Drill (bodyweight)", prescription: "10 reps" },
          { name: "Shoulder W", prescription: "15 reps" },
        ],
      },
      {
        type: "main",
        label: "3-Round Circuit",
        durationMinutes: 18,
        rounds: 3,
        restNote: "Rest ~90 sec between rounds",
        exercises: [
          { name: "Kettlebell Deadlift", prescription: "12 reps" },
          { name: "Ring Row", prescription: "10 reps" },
          { name: "Kettlebell Swing", prescription: "15 reps" },
          { name: "Single-Leg RDL", prescription: "8 reps each leg" },
          { name: "Dead Hang", prescription: "20 sec" },
        ],
      },
      {
        type: "cooldown",
        label: "Cool-down",
        durationMinutes: 3,
        exercises: [
          { name: "Hip Flexor Stretch", prescription: "30 sec each side" },
          { name: "Hamstring Stretch", prescription: "30 sec each leg" },
          { name: "Lat Stretch", prescription: "30 sec each side" },
        ],
      },
    ],
  },
  {
    id: "C",
    letter: "C",
    name: "Push & Squat",
    description: "Quads, chest, and shoulders. High anterior-chain volume.",
    totalMinutes: 25,
    color: "blue",
    sections: [
      {
        type: "warmup",
        label: "Warm-up",
        durationMinutes: 4,
        exercises: [
          { name: "Squat to Stand", prescription: "8 reps" },
          { name: "World's Greatest Stretch", prescription: "4 reps each side" },
          { name: "Push-up to Cobra", prescription: "5 reps" },
          { name: "Shoulder Rolls", prescription: "30 sec each way" },
        ],
      },
      {
        type: "main",
        label: "3-Round Circuit",
        durationMinutes: 18,
        rounds: 3,
        restNote: "Rest ~90 sec between rounds",
        exercises: [
          { name: "Goblet Squat", prescription: "15 reps" },
          { name: "Push-up", prescription: "12 reps" },
          { name: "Box Step-Up", prescription: "10 reps each leg" },
          { name: "Ring Push-up", prescription: "8 reps" },
          { name: "Wall Sit", prescription: "30 sec" },
        ],
      },
      {
        type: "cooldown",
        label: "Cool-down",
        durationMinutes: 3,
        exercises: [
          { name: "Quad Stretch", prescription: "30 sec each leg" },
          { name: "Pigeon Pose", prescription: "45 sec each side" },
          { name: "Chest Opener", prescription: "30 sec" },
        ],
      },
    ],
  },
  {
    id: "D",
    letter: "D",
    name: "Back-Friendly",
    description: "Glute-led, spine-neutral movements. Safe when your back is talking.",
    totalMinutes: 25,
    color: "warm",
    sections: [
      {
        type: "warmup",
        label: "Warm-up",
        durationMinutes: 4,
        exercises: [
          { name: "Pelvic Tilt", prescription: "15 reps" },
          { name: "Glute Bridge", prescription: "15 reps" },
          { name: "Bird Dog", prescription: "8 reps each side" },
          { name: "Dead Bug", prescription: "45 sec" },
        ],
      },
      {
        type: "main",
        label: "3-Round Circuit",
        durationMinutes: 18,
        rounds: 3,
        restNote: "Rest ~90 sec between rounds",
        exercises: [
          { name: "Glute Bridge", prescription: "15 reps" },
          { name: "Plank Shoulder Tap", prescription: "12 reps each side" },
          { name: "Suitcase Carry", prescription: "30 sec each side" },
          { name: "Modified Push-up", prescription: "10 reps" },
          { name: "Step-Up (low box)", prescription: "10 reps each leg" },
        ],
      },
      {
        type: "cooldown",
        label: "Cool-down",
        durationMinutes: 3,
        exercises: [
          { name: "Knee-to-Chest Stretch", prescription: "30 sec each leg" },
          { name: "Piriformis Stretch", prescription: "30 sec each side" },
          { name: "Cat-Cow", prescription: "1 min" },
        ],
      },
    ],
  },
];
